x-airflow-common:
  &airflow-common
  environment:
    AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: "mysql+mysqlconnector://airflow_user:${MYSQL_PASSWORD}@mysql:3306/airflow_db"
    AIRFLOW__CORE__EXECUTOR: "LocalExecutor"
    AIRFLOW__CORE__FERNET_KEY: ${AIRFLOW_FERNET_KEY}
  env_file:
    - .env
  depends_on:
    mysql:
      condition: service_healthy
  volumes:
    - ./src:/opt/airflow/src
    - ./dags:/opt/airflow/dags
    - ./logs:/opt/airflow/logs
    - ./plugins:/opt/airflow/plugins
    - ./requirements.txt:/requirements.txt

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: airflow_db
      MYSQL_USER: airflow_user
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "MYSQL_PWD=${MYSQL_PASSWORD} mysqladmin ping -h localhost -u airflow_user || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 20

  airflow-init:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: airflow-init
    <<: *airflow-common
    entrypoint: >
      bash -c "airflow db reset -y &&
               airflow db migrate &&
               airflow users create --username ${_AIRFLOW_WWW_USER_USERNAME:-airflow} --password ${_AIRFLOW_WWW_USER_PASSWORD:-airflow} --firstname Admin --lastname User --role Admin --email admin@example.com"
    healthcheck:
      test: ["CMD", "airflow", "db", "check"]
      interval: 10s
      retries: 10

  airflow-scheduler:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: airflow-scheduler
    <<: *airflow-common
    depends_on:
      airflow-init:
        condition: service_healthy
    command: >
      bash -c "airflow scheduler"

  airflow-webserver:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: airflow-webserver
    <<: *airflow-common
    depends_on:
      airflow-init:
        condition: service_healthy
    ports:
      - "8080:8080"
    command: >
      bash -c "airflow webserver"

volumes:
  mysql_data:
